export const userInputs = [
	{
		id: 1,
		label: "Name and surname",
		type: "text",
		placeholder: "John Doe",
	},
	{
		id: 2,
		label: "Home number and street",
		type: "text",
		placeholder: "1 Võ Văn Ngân",
	},
	{
		id: 3,
		label: "Ward",
		type: "text",
		placeholder: "Phường Linh Chiểu",
	},
	{
		id: 4,
		label: "District",
		type: "text",
		placeholder: "Quận Thủ Đức",
	},
	{
		id: 5,
		label: "City",
		type: "text",
		placeholder: "TP Hồ Chí Minh",
	},
];

export const addProductInputs = [
	{
		id: 1,
		label: "Tên sản phẩm",
		type: "text",
		placeholder: "Apple Macbook Pro",
		title: "title",
	},
	{
		id: 2,
		label: "Slug",
		type: "text",
		placeholder: "apple-macbook-pro",
		title: "slug",
	},
	{
		id: 3,
		label: "Mô tả",
		type: "text",
		placeholder: "Mô tả",
		title: "info",
	},
	{
		id: 4,
		label: "Hãng sản xuất",
		type: "text",
		placeholder: "Hãng sản xuất   ",
		title: "brand",
	},
	{
		id: 5,
		label: "Giá bán sản phẩm",
		type: "number",
		placeholder: "100",
		title: "listPrice",
	},
	{
		id: 6,
		label: "Giá nhập sản phẩm",
		type: "number",
		placeholder: "100",
		title: "standCost",
	},
	{
		id: 7,
		label: "Màu sắc",
		type: "text",
		placeholder: "Màu sắc",
		title: "colors",
	},

	{
		id: 8,
		label: "Màn hình",
		title: "screen",
		placeholder: "Màn hình",
		type: "text",
	},
	{
		id: 9,
		label: "Hệ điều hành",
		title: "os",
		placeholder: "Hệ điều hành",
		type: "text",
	},
	{
		id: 10,
		label: "Camera sau",
		title: "cameraBehind",
		placeholder: "Camera sau",
		type: "text",
	},
	{
		id: 11,
		label: "Camera trước",
		title: "cameraBefore",
		placeholder: "Camera trước",
		type: "text",
	},
	{
		id: 12,
		label: "Chip",
		title: "chip",
		placeholder: "Chip",
		type: "text",
	},
	{
		id: 13,
		label: "Sim",
		title: "sim",
		placeholder: "Sim",
		type: "text",
	},
	{
		id: 14,
		label: "Pin, Sạc",
		title: "pin",
		placeholder: "Pin sạc",
		type: "text",
	},
	{
		id: 15,
		label: "Ram",
		title: "ram",
		placeholder: "Ram",
		type: "text",
	},
	{
		id: 16,
		label: "Rom",
		title: "rom",
		placeholder: "Rom",
		type: "text",
	},
];

export const productInputs = [
	{
		id: 1,
		label: "Tên sản phẩm",
		type: "text",
		placeholder: "Apple Macbook Pro",
		title: "title",
	},
	{
		id: 2,
		label: "Slug",
		type: "text",
		placeholder: "apple-macbook-pro",
		title: "slug",
	},
	{
		id: 3,
		label: "Mô tả",
		type: "text",
		placeholder: "Mô tả",
		title: "info",
	},
	{
		id: 4,
		label: "Hãng sản xuất",
		type: "text",
		placeholder: "Hãng sản xuất   ",
		title: "brand",
	},
	{
		id: 5,
		label: "Giá bán sản phẩm",
		type: "number",
		placeholder: "100",
		title: "listPrice",
	},
	{
		id: 6,
		label: "Giá nhập sản phẩm",
		type: "number",
		placeholder: "100",
		title: "standCost",
	},
	{
		id: 7,
		label: "Màu sắc",
		type: "text",
		placeholder: "Màu sắc",
		title: "colors",
	},
];

export const typeProduct = [
	{
		id: 1,
		label: "Điện thoại",
		type: "dienthoai",
	},
	{
		id: 2,
		label: "Laptop",
		type: "laptop",
	},
	{
		id: 3,
		label: "Phụ kiện",
		type: "phukien",
	},
	{
		id: 4,
		label: "Đồng hồ",
		type: "watch",
	},
	{
		id: 5,
		label: "Đồng hồ thông minh",
		type: "smartwatch",
	},
];
export const phoneProduct = [
	{
		id: 1,
		label: "Màn hình",
		title: "screen",
		placeholder: "Màn hình",
		type: "text",
	},
	{
		id: 2,
		label: "Hệ điều hành",
		title: "os",
		placeholder: "Hệ điều hành",
		type: "text",
	},
	{
		id: 3,
		label: "Camera sau",
		title: "cameraBehind",
		placeholder: "Camera sau",
		type: "text",
	},
	{
		id: 4,
		label: "Camera trước",
		title: "cameraBefore",
		placeholder: "Camera trước",
		type: "text",
	},
	{
		id: 5,
		label: "Chip",
		title: "chip",
		placeholder: "Chip",
		type: "text",
	},
	{
		id: 6,
		label: "Sim",
		title: "sim",
		placeholder: "Sim",
		type: "text",
	},
	{
		id: 7,
		label: "Pin, Sạc",
		title: "pin",
		placeholder: "Pin sạc",
		type: "text",
	},
];
export const laptopProduct = [
	{
		id: 1,
		label: "Màn hình",
		title: "screen",
		placeholder: "Màn hình",
		type: "text",
	},
	{
		id: 2,
		label: "Hệ điều hành",
		title: "os",
		placeholder: "Hệ điều hành",
		type: "text",
	},
	{
		id: 3,
		label: "Chip",
		title: "chip",
		placeholder: "Chip",
		type: "text",
	},
	{
		id: 4,
		label: "Pin, Sạc",
		title: "pin",
		placeholder: "Pin sạc",
		type: "text",
	},
	{
		id: 5,
		label: "Card màn hình",
		title: "graphicCard",
		placeholder: "RTX 3080 Ti",
		type: "text",
	},
	{
		id: 6,
		label: "Thiết kế",
		title: "design",
		placeholder: "Vỏ nhựa",
		type: "text",
	},
	{
		id: 7,
		label: "Cổng kết nối",
		title: "portConect",
		placeholder: "Jack tai nghe 3.5 mm",
		type: "text",
	},
];
export const watchProduct = [
	{
		id: 1,
		label: "Giới tính",
		title: "sex",
		placeholder: "VD: Nam",
		type: "text",
	},
	{
		id: 2,
		label: "Đường kính mặt",
		title: "diameter",
		placeholder: "29 mm",
		type: "text",
	},
	{
		id: 3,
		label: "Loại mặt đồng hồ",
		title: "typeFaceWatch",
		placeholder: "Điện tử",
		type: "text",
	},
	{
		id: 4,
		label: "Chất liệu dây",
		title: "material",
		placeholder: "Da tổng hợp",
		type: "text",
	},
	{
		id: 5,
		label: "Bộ máy",
		title: "batery",
		placeholder: "Pin",
		type: "text",
	},
	{
		id: 6,
		label: "Chống nước",
		title: "waterProof",
		placeholder: "Đi mưa, tắm",
		type: "text",
	},
];
export const smartWatchProduct = [
	{
		id: 1,
		label: "Giới tính",
		title: "sex",
		placeholder: "VD: Nam",
		type: "text",
	},
	{
		id: 2,
		label: "Mặt",
		title: "face",
		placeholder: " Ion-X strengthened glass 42 mm ",
		type: "text",
	},
	{
		id: 3,
		label: "Kết nối hệ điều hành",
		title: "conectOS",
		placeholder: "Iphone",
		type: "text",
	},
	{
		id: 4,
		label: "Thời lượng pin",
		title: "battery",
		placeholder: "5 ngày",
		type: "text",
	},
	{
		id: 5,
		label: "Tính năng cho sức khỏe",
		title: "healcare",
		placeholder: "Đo nhịp tim",
		type: "text",
	},
];
export const typeAccessory = [
	{
		id: 1,
		label: "Sạc dự phòng",
		title: "sacduphong",
	},
	{
		id: 2,
		label: "Sạc, cáp",
		title: "cap",
	},
	{
		id: 3,
		label: "Ốp lưng điện thoại",
		title: "oplungdienthoai",
	},
	{
		id: 4,
		label: "Ốp lưng máy tính bảng",
		title: "oplungmaytinhbang",
	},
	{
		id: 5,
		label: "Miếng dán màn hình",
		title: "miengdanmanhinh",
	},
	{
		id: 6,
		label: "Chuột",
		title: "chuot",
	},
	{
		id: 7,
		label: "Bàn phím",
		title: "banphim",
	},
	{
		id: 8,
		label: "Tai nghe",
		title: "tainghe",
	},
	{
		id: 9,
		label: "Loa",
		title: "loa",
	},
	{
		id: 10,
		label: "Webcam",
		title: "webcam",
	},
];
